// Guide data module — no React, no rendering. Pure structured data.

export const FILE_GUIDE = {
  sellerSprite: {
    label: 'SellerSprite',
    labelEn: '卖家精灵',
    files: [
      {
        pattern: 'ExpandKeywords-*.xlsx',
        tool: 'Reverse ASIN (反查ASIN)',
        steps: [
          '打开 SellerSprite → 反查ASIN (Reverse ASIN)',
          '输入 ASIN → 设置 US 市场 + Last 30 days',
          '点击搜索 → 等待结果加载',
          '点击 Export 下载 .xlsx 文件',
        ],
        runFor: '自己的 ASIN + 每个竞品 ASIN（共 5 次导出）',
        asins: ['See config.json for current product + competitor ASINs'],
        feedsTabs: ['竞品分析', '词库整理', 'Gap分析'],
        expectedCols: 32,
        expectedRows: '500-3000',
        notes: '多 sheet 格式，每个 sheet 可能对应不同变体。确保导出全部 sheet。',
      },
      {
        pattern: 'KeywordMining-*.xlsx',
        tool: 'Keyword Mining (关键词挖掘)',
        steps: [
          '打开 SellerSprite → 关键词挖掘 (Keyword Mining)',
          '输入种子关键词（如 "silk blouse"）',
          '设置 US 市场 + Last 30 days → 搜索',
          '点击 Export 下载 .xlsx 文件',
        ],
        runFor: '每个种子关键词各一次',
        seedKeywords: ['See config.json seed_keywords for current product'],
        feedsTabs: ['词库整理'],
        expectedCols: 33,
        expectedRows: '最多 3000',
        notes: '行数越多越好，有助于构建完整的关键词库。',
      },
      {
        pattern: 'CompareKeywords-*.xlsx',
        tool: 'Traffic Comparison (流量对比)',
        steps: [
          '打开 SellerSprite → 流量对比 (Traffic Comparison)',
          '输入自己的 ASIN + 所有竞品 ASIN',
          '点击对比 → 等待结果',
          '点击 Export 下载 .xlsx 文件',
        ],
        runFor: '一次（所有 ASIN 在同一次导出中）',
        feedsTabs: ['流量入口'],
        expectedCols: '因 ASIN 数量而异（交替列格式）',
        expectedRows: '500-2000',
        notes: '多 ASIN 交替列格式，解析器会自动处理。',
      },
      {
        pattern: 'AdsInsights-*.xlsx',
        tool: 'Ads Insights (广告洞察)',
        steps: [
          '打开 SellerSprite → 广告洞察 (Ads Insights)',
          '输入自己的 ASIN → 搜索',
          '选择时间范围（推荐 8-12 周）',
          '点击 Export 下载 .xlsx 文件',
        ],
        runFor: '仅自己的 ASIN',
        feedsTabs: ['广告指标监测'],
        expectedCols: '透视表格式（每周 5 列）',
        expectedRows: '100-500 关键词 × 多周',
        notes: '关键：这是透视格式（pivot format），不是标准表格。第 0 行是周标题，第 1 行是 ASIN，第 3+ 行才是数据。每个 sheet = 不同变体。',
      },
      {
        pattern: 'Competitor-*.xlsx',
        tool: 'Competitor Research (竞品调研)',
        steps: [
          '打开 SellerSprite → 竞品调研 (Competitor Research)',
          '输入类目或关键词搜索竞品',
          '筛选结果（价格范围、评分等）',
          '点击 Export 下载 .xlsx 文件',
        ],
        runFor: '一次（按类目搜索）',
        feedsTabs: ['竞品分析'],
        expectedCols: 64,
        expectedRows: '最多 3000',
        notes: '64 列，包含详细的产品数据（品牌、价格、销量、BSR 等）。',
      },
      {
        pattern: 'KeywordResearch-*.xlsx',
        tool: 'Keyword Research (关键词调研)',
        steps: [
          '打开 SellerSprite → 关键词调研 (Keyword Research)',
          '选择市场/类目',
          '点击 Export 下载 .xlsx 文件',
        ],
        runFor: '一次（按市场）',
        feedsTabs: ['词库整理'],
        expectedCols: '标准表格',
        expectedRows: '500-2000',
        notes: '标准表格格式，解析较简单。',
      },
    ],
  },
  sellerCentral: {
    label: 'Seller Central',
    labelEn: '卖家后台',
    files: [
      {
        pattern: 'BusinessReport*.csv',
        report: 'Detail Page Sales & Traffic by Child ASIN',
        steps: [
          '登录 Seller Central → Reports → Business Reports',
          '选择 "By Child Item" (Detail Page Sales and Traffic by Child Item)',
          '设置日期范围: Last 30 days',
          '点击 Download (.csv)',
        ],
        dateRange: 'Last 30 days',
        feedsTabs: ['竞品分析', '产品清单', '定价策略'],
        gotchas: [
          '列名有尾随空格（如 "7 Day Total Sales "）',
          '金额带 $ 前缀（如 "$989.91"）',
          '百分比带 % 后缀（如 "98.2%"）',
        ],
        notes: '这是最重要的文件之一，提供自己产品的销售和流量数据。',
      },
      {
        pattern: 'SpSearchTerm*.csv',
        report: 'SP Search Term Report',
        steps: [
          '登录 Seller Central → Advertising → Reports',
          '点击 "Create Report"',
          '选择 Report type: "Search term"',
          '选择 Report period: Last 30-60 days',
          '生成后下载 .csv 文件',
        ],
        dateRange: 'Last 30-60 days',
        feedsTabs: ['广告指标监测', '词库整理'],
        gotchas: [
          '列名有尾随空格！务必 .strip()',
          '"--" 表示空值/零',
          '金额带 $ 前缀',
        ],
        notes: '包含每个搜索词的广告表现数据（曝光、点击、ACoS 等）。',
      },
      {
        pattern: 'SpCampaign*.csv',
        report: 'SP Campaign Report',
        steps: [
          '登录 Seller Central → Advertising → Reports',
          '点击 "Create Report"',
          '选择 Report type: "Campaign"',
          '选择 Report period: Last 30-60 days',
          '生成后下载 .csv 文件',
        ],
        dateRange: 'Last 30-60 days',
        feedsTabs: ['广告指标监测', '定价策略'],
        gotchas: [
          '同样有尾随空格和 $ 前缀问题',
          '"--" 表示空值',
        ],
        notes: '广告活动级别的花费和效果数据。',
      },
      {
        pattern: 'FBAFee*.csv',
        report: 'FBA Fee Preview',
        steps: [
          '登录 Seller Central → Reports → Fulfillment',
          '找到 "Fee Preview" 报告',
          '点击 Download',
        ],
        dateRange: 'Current（当前快照）',
        feedsTabs: ['定价策略'],
        gotchas: [
          '"--" 表示空值',
          '费用可能因尺寸/重量变化',
        ],
        notes: 'FBA 配送费和仓储费明细，用于定价策略中的成本分解。',
      },
    ],
  },
};

export const METRIC_DEFINITIONS = {
  competitors: {
    title: '竞品分析',
    description: '对比自己的产品与4个竞品的核心运营指标',
    sourceFiles: ['ExpandKeywords-*.xlsx', 'Competitor-*.xlsx', 'BusinessReport*.csv'],
    metrics: [
      { name: '品牌', en: 'Brand', definition: '产品品牌名称' },
      { name: 'ASIN', en: 'ASIN', definition: 'Amazon Standard Identification Number，产品唯一标识' },
      { name: '价格', en: 'Price', definition: '当前 listing 标价（美元）' },
      { name: '评分', en: 'Rating', definition: '顾客评分（1-5星），4.0+ 为健康' },
      { name: '评论数', en: 'Reviews', definition: '产品评论总数，越多表示销售历史越长/销量越大' },
      { name: '月销量', en: 'Monthly Sales', definition: 'SellerSprite 估算的近30天销量（非精确值，仅供参考）' },
      { name: '月销售额', en: 'Monthly Revenue', definition: '月销量 × 价格的估算值' },
      { name: '类目BSR', en: 'Category BSR', definition: 'Best Sellers Rank — 在最大类目中的排名，数字越小 = 销量越高' },
      { name: '子类目BSR', en: 'Sub-category BSR', definition: '子类目排名，更精准反映细分市场地位' },
      { name: '上架日期', en: 'Launch Date', definition: '产品首次上架 Amazon 的日期' },
      { name: '变体数', en: 'Variations', definition: '颜色/尺寸等变体数量' },
      { name: '前五核心流量词', en: 'Top 5 Traffic Keywords', definition: '按 traffic share 排序的前5个关键词，揭示主要流量来源' },
      { name: '流量关键词数', en: 'Keyword Count', definition: '该 ASIN 获得排名的关键词总数' },
    ],
  },
  products: {
    title: '产品清单',
    description: '4价格场景成本模型 + 变体销售明细',
    sourceFiles: ['BusinessReport*.csv', 'FBAFee*.csv'],
    metrics: [
      { name: '4 价格场景', en: '4 Price Scenarios', definition: '$45.99（竞争价）、$55.99（中间价）、$65.99（优质价）、$109.99（当前价）— 对比不同定价下的利润空间' },
      { name: '成品成本', en: 'Unit Cost', definition: '每件产品的生产/采购成本（蓝色+黄色 = 可编辑）' },
      { name: 'Amazon佣金(17%)', en: 'Referral Fee', definition: 'Amazon 按售价收取的类目佣金（服装类通常 17%）' },
      { name: 'FBA配送费', en: 'FBA Fee', definition: 'Amazon 代发货的配送费用，按尺寸和重量计算' },
      { name: '月仓储费', en: 'Monthly Storage', definition: 'Amazon 仓库按体积收取的月度仓储费' },
      { name: '毛利润', en: 'Gross Profit', definition: '售价 - 总成本 = 每单位利润' },
      { name: '毛利率', en: 'Gross Margin', definition: '毛利润 ÷ 售价 × 100%，建议 > 30%' },
      { name: 'CVR', en: 'Conversion Rate', definition: '订单数 ÷ 页面访问数（Sessions）× 100%' },
    ],
  },
  keywords: {
    title: '词库整理',
    description: '6000+ 关键词的分类、排名和广告数据',
    sourceFiles: ['ExpandKeywords-*.xlsx', 'KeywordMining-*.xlsx', 'KeywordResearch-*.xlsx', 'SpSearchTerm*.csv'],
    metrics: [
      { name: '一级分类', en: 'Primary Classification', definition: '按月搜索量自动分类：大词（>50K）、核心关键词（10K-50K）、功能/场景/人群词（3K-10K）、长尾词（<3K 或 4+ 个单词）、竞品品牌词（含竞品品牌名）' },
      { name: '二级分类', en: 'Secondary Classification', definition: '按转化潜力分类：主力出单词（购买率>2% 且排名≤20）、潜力测试词（搜索>5K 且排名>50）、流量/防御词（搜索>10K 且购买率<0.5%）、无效/亏损词（无购买、无排名、CPC>$2）' },
      { name: '月搜索量', en: 'Monthly Searches', definition: 'Amazon 上该关键词每月被搜索的次数（SellerSprite 估算值）' },
      { name: '购买率', en: 'Purchase Rate', definition: '搜索该词后实际购买的用户比例。>2% 为优质转化词' },
      { name: 'CPC / PPC竞价', en: 'PPC Bid', definition: 'PPC 广告的建议竞价（精确匹配），反映关键词竞争程度' },
      { name: '自然排名', en: 'Organic Rank', definition: '该关键词的自然搜索排名。≤20 为优秀，>50 需要优化' },
      { name: '广告排名', en: 'Sponsored Rank', definition: '该关键词的广告位排名' },
      { name: '数据来源', en: 'Data Source', definition: '数据来自哪个文件（ExpandKeywords / KeywordMining / SearchTerm 等）' },
    ],
  },
  ads: {
    title: '广告指标监测',
    description: '搜索词广告表现 + 广告活动概览',
    sourceFiles: ['AdsInsights-*.xlsx', 'SpSearchTerm*.csv', 'SpCampaign*.csv'],
    metrics: [
      { name: '曝光', en: 'Impressions', definition: '广告被展示的次数' },
      { name: '点击', en: 'Clicks', definition: '广告被点击的次数' },
      { name: 'CTR', en: 'Click-Through Rate', definition: '点击 ÷ 曝光 × 100%。衡量广告相关性。>0.5% 为正常，>1% 为优秀' },
      { name: 'CPC', en: 'Cost Per Click', definition: '每次点击的平均花费' },
      { name: 'ACoS', en: 'Advertising Cost of Sales', definition: '广告花费 ÷ 广告归因销售额 × 100%。<20% 健康，20-30% 需关注，>30% 需优化' },
      { name: 'CVR', en: 'Conversion Rate', definition: '订单 ÷ 点击 × 100%。衡量 listing 转化能力' },
      { name: '订单', en: 'Orders', definition: '通过该搜索词/广告活动产生的订单数' },
      { name: '销售额', en: 'Sales', definition: '通过广告产生的归因销售额' },
    ],
  },
  pricing: {
    title: '定价策略',
    description: '每个变体（Child ASIN）的成本分解和利润分析',
    sourceFiles: ['BusinessReport*.csv', 'FBAFee*.csv', 'SpCampaign*.csv'],
    metrics: [
      { name: '平均售价', en: 'Avg Selling Price', definition: '销售额 ÷ 销量，该变体的实际平均成交价' },
      { name: '采购占比', en: 'Unit Cost %', definition: '单位成本 ÷ 平均售价。理想值 < 25%' },
      { name: '头程占比', en: 'Inbound Shipping %', definition: '单位头程运费 ÷ 平均售价' },
      { name: '配送占比', en: 'FBA Fee %', definition: 'FBA 配送费 ÷ 平均售价' },
      { name: '佣金占比', en: 'Referral Fee %', definition: 'Amazon 类目佣金 ÷ 平均售价（通常 17%）' },
      { name: '仓储占比', en: 'Storage %', definition: '月仓储费 ÷ 平均售价' },
      { name: 'ACoS', en: 'Advertising Cost of Sales', definition: '广告花费 ÷ 广告销售额。<20% 健康' },
      { name: 'TACoS', en: 'Total ACoS', definition: '总广告花费 ÷ 总销售额（含自然销售）。<15% 为健康。TACoS 越低说明对广告的依赖越小，自然流量越强' },
    ],
  },
  traffic: {
    title: '流量入口',
    description: '各流量渠道的策略矩阵',
    sourceFiles: ['CompareKeywords-*.xlsx', 'ExpandKeywords-*.xlsx', 'SpSearchTerm*.csv'],
    metrics: [
      { name: '流量入口', en: 'Traffic Channel', definition: '流量来源渠道（自然搜索、广告、关联流量、站外等）' },
      { name: '流量来源', en: 'Traffic Source', definition: '具体流量来源类型' },
      { name: '方案', en: 'Strategy', definition: '针对该渠道的具体运营方案，包含推荐关键词和搜索量数据' },
    ],
  },
  gap: {
    title: 'Gap分析',
    description: '与主要竞品的关键词覆盖差距分析',
    sourceFiles: ['ExpandKeywords-*.xlsx (自己 + 竞品)'],
    metrics: [
      { name: 'MISSING', en: 'Missing Keywords', definition: '竞品有排名而我方没有的关键词。最高优先级（1.0x 乘数）— 需要新建广告活动或优化 listing' },
      { name: 'CATCHUP', en: 'Catch-up Keywords', definition: '双方都有排名但竞品领先。中等优先级（0.5x）— 需要加大广告投放或优化内容' },
      { name: 'DEFEND', en: 'Defend Keywords', definition: '我方排名好而竞品较弱。低优先级（0.2x）— 维持现有优势，防御性投放' },
      { name: '优先级分数', en: 'Priority Score', definition: 'monthly_searches × purchase_rate × gap_type_multiplier。分数越高 = 越值得投入资源' },
      { name: '建议操作', en: 'Recommended Action', definition: '基于 gap 类型和优先级给出的具体操作建议' },
      { name: '月搜索量', en: 'Monthly Searches', definition: '该关键词的月搜索量' },
      { name: '购买率', en: 'Purchase Rate', definition: '搜索后的购买转化率' },
      { name: 'PPC竞价', en: 'PPC Bid', definition: '广告竞价参考值，反映竞争程度' },
    ],
  },
};

export const DATA_FLOW = [
  {
    file: 'ExpandKeywords-*.xlsx',
    source: 'SellerSprite',
    parser: 'parse_expand_keywords()',
    processors: ['keywords.py', 'competitors.py', 'gap_analysis.py'],
    outputTabs: ['竞品分析', '词库整理', 'Gap分析'],
    description: '反查 ASIN 的流量关键词数据。是关键词库和 Gap 分析的核心来源。',
  },
  {
    file: 'KeywordMining-*.xlsx',
    source: 'SellerSprite',
    parser: 'parse_keyword_mining()',
    processors: ['keywords.py'],
    outputTabs: ['词库整理'],
    description: '通过种子关键词挖掘相关词。扩展关键词库覆盖面。',
  },
  {
    file: 'CompareKeywords-*.xlsx',
    source: 'SellerSprite',
    parser: 'parse_compare_keywords()',
    processors: ['keywords.py', 'traffic.py'],
    outputTabs: ['词库整理', '流量入口'],
    description: '多 ASIN 流量来源对比。用于制定流量入口策略。',
  },
  {
    file: 'AdsInsights-*.xlsx',
    source: 'SellerSprite',
    parser: 'parse_ads_insights()',
    processors: ['ads.py'],
    outputTabs: ['广告指标监测'],
    description: '广告关键词的周度排名和搜索量趋势（透视表格式）。',
  },
  {
    file: 'Competitor-*.xlsx',
    source: 'SellerSprite',
    parser: 'parse_competitor()',
    processors: ['competitors.py'],
    outputTabs: ['竞品分析'],
    description: '竞品产品详情（64列），包含品牌、价格、销量、BSR 等。',
  },
  {
    file: 'KeywordResearch-*.xlsx',
    source: 'SellerSprite',
    parser: 'parse_keyword_research()',
    processors: ['keywords.py'],
    outputTabs: ['词库整理'],
    description: '市场/类目级别的关键词数据，补充词库。',
  },
  {
    file: 'BusinessReport*.csv',
    source: 'Seller Central',
    parser: 'parse_business_report()',
    processors: ['competitors.py', 'pricing.py'],
    outputTabs: ['竞品分析', '产品清单', '定价策略'],
    description: '自己产品的销售和流量数据（Sessions、订单、销售额等）。最重要的文件之一。',
  },
  {
    file: 'SpSearchTerm*.csv',
    source: 'Seller Central',
    parser: 'parse_search_term_report()',
    processors: ['ads.py', 'keywords.py'],
    outputTabs: ['广告指标监测', '词库整理'],
    description: '搜索词级别的广告表现（曝光、点击、ACoS 等）。',
  },
  {
    file: 'SpCampaign*.csv',
    source: 'Seller Central',
    parser: 'parse_campaign_report()',
    processors: ['ads.py', 'pricing.py'],
    outputTabs: ['广告指标监测', '定价策略'],
    description: '广告活动级别的花费和效果数据。',
  },
  {
    file: 'FBAFee*.csv',
    source: 'Seller Central',
    parser: 'parse_fba_fee_preview()',
    processors: ['pricing.py'],
    outputTabs: ['定价策略'],
    description: 'FBA 配送费和仓储费明细，用于成本分解。',
  },
];
