#!/usr/bin/env node
// =============================================================================
// 肯葳科技亚马逊自动运营系统 — Windows Desktop Launcher
// Compile to .exe with: npx pkg launcher.js --targets node18-win-x64 -o EcommerceAutomation.exe
// =============================================================================

const { execSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const http = require('http');

// Resolve project root (launcher is at desktop/windows/)
const SCRIPT_DIR = __dirname;
const PROJECT_DIR = path.resolve(SCRIPT_DIR, '..', '..');

// --- Helpers ---
function showDialog(message, title = '肯葳自动运营系统') {
  try {
    execSync(
      `powershell -Command "[System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms') | Out-Null; [System.Windows.Forms.MessageBox]::Show('${message.replace(/'/g, "''")}', '${title}', 'OK', 'Information')"`,
      { stdio: 'ignore' }
    );
  } catch {}
}

function showError(message) {
  try {
    execSync(
      `powershell -Command "[System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms') | Out-Null; [System.Windows.Forms.MessageBox]::Show('${message.replace(/'/g, "''")}', '肯葳自动运营系统', 'OK', 'Error')"`,
      { stdio: 'ignore' }
    );
  } catch {}
}

function openBrowser(url) {
  try { execSync(`start "" "${url}"`, { stdio: 'ignore' }); } catch {}
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function healthCheck() {
  return new Promise((resolve) => {
    http.get('http://localhost:3000/api/status', (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(true));
    }).on('error', () => resolve(false));
  });
}

// --- Main ---
async function main() {
  process.chdir(PROJECT_DIR);

  // Step 1: Check Docker
  try {
    execSync('docker --version', { stdio: 'ignore' });
  } catch {
    showError('Docker 未安装！\n\n请先安装 Docker Desktop：\nhttps://www.docker.com/products/docker-desktop/\n\n安装完成后重新打开此应用。');
    openBrowser('https://www.docker.com/products/docker-desktop/');
    process.exit(1);
  }

  // Step 2: Start Docker if not running
  try {
    execSync('docker info', { stdio: 'ignore' });
  } catch {
    try {
      execSync('start "" "Docker Desktop"', { stdio: 'ignore' });
    } catch {}

    let waited = 0;
    while (waited < 60) {
      await sleep(2000);
      waited += 2;
      try {
        execSync('docker info', { stdio: 'ignore' });
        break;
      } catch {}
    }

    if (waited >= 60) {
      showError('Docker Desktop 启动超时。\n\n请手动打开 Docker Desktop，等待其完全启动后，再重新打开此应用。');
      process.exit(1);
    }
  }

  // Step 3: Create directories
  for (const dir of ['data', 'inputs/sellersprite', 'inputs/seller-central', 'outputs', 'processed', 'logs']) {
    fs.mkdirSync(path.join(PROJECT_DIR, dir), { recursive: true });
  }

  // Step 4: Generate .env
  const setupFile = path.join(PROJECT_DIR, 'data', 'setup.json');
  const envFile = path.join(PROJECT_DIR, '.env');

  if (fs.existsSync(setupFile)) {
    const setup = JSON.parse(fs.readFileSync(setupFile, 'utf-8'));
    const envContent = [
      '# Auto-generated by desktop launcher',
      `ADSPOWER_API_URL=${setup.api_url || 'http://host.docker.internal:50325'}`,
      `ADSPOWER_API_KEY=${setup.api_key || ''}`,
      `ADSPOWER_PROFILE_ID=${setup.profile_id || ''}`,
      'NODE_ENV=production',
      'PORT=3000',
    ].join('\n');
    fs.writeFileSync(envFile, envContent);
  } else if (!fs.existsSync(envFile)) {
    const envContent = [
      'ADSPOWER_API_URL=http://host.docker.internal:50325',
      'ADSPOWER_API_KEY=',
      'ADSPOWER_PROFILE_ID=',
      'NODE_ENV=production',
      'PORT=3000',
    ].join('\n');
    fs.writeFileSync(envFile, envContent);
  }

  // Step 5: Check if already running
  try {
    const ps = execSync('docker compose ps --format json', { encoding: 'utf-8' });
    if (ps.includes('"running"')) {
      openBrowser('http://localhost:3000');
      process.exit(0);
    }
  } catch {}

  // Step 6: Start container
  try {
    execSync('docker compose up -d --build', { stdio: 'ignore', timeout: 300000 });
  } catch (e) {
    showError(`系统启动失败。\n\n错误: ${e.message}\n\n请在命令提示符中运行以下命令查看详情：\ncd ${PROJECT_DIR} && docker compose logs`);
    process.exit(1);
  }

  // Step 7: Health check
  let waited = 0;
  const maxWait = 180;
  while (waited < maxWait) {
    if (await healthCheck()) break;
    await sleep(3000);
    waited += 3;
  }

  if (waited >= maxWait) {
    showError('系统启动超时。\n\n请在命令提示符中运行：\ndocker compose logs');
    process.exit(1);
  }

  // Step 8: Open browser
  openBrowser('http://localhost:3000');
}

main().catch(e => {
  showError(`启动错误: ${e.message}`);
  process.exit(1);
});
